# Generated by Django 5.2 on 2025-04-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='email_adress',
            new_name='email_address',
        ),
    ]
